version: '3.8'

services:
  oauth2-mock:
    image: ghcr.io/navikt/mock-oauth2-server:2.1.0
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080
      LOG_LEVEL: debug
      ISSUER_URL: "http://localhost:8080/default"

networks:
  default:
    driver: bridge