version: '3.8'

services:
  oauth2-mock:
    image: ghcr.io/navikt/mock-oauth2-server:2.1.0
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080

  grpc-auth-test:
    build: .
    depends_on:
      - oauth2-mock
    command: cargo test --test auth_test -- --nocapture
    volumes:
      - .:/usr/src/app
      - target:/usr/src/app/target