[server]
host = "0.0.0.0"
port = 50052

[auth]
provider_type = "auth0"

[auth.auth0]
domain = "localhost:8080"
client_id = "test-client-id"
client_secret = "test-client-secret"
audience = "test-audience"

[auth.keycloak]
realm = "test-realm"
auth_server_url = "http://localhost:8080/auth"
client_id = "test-client-id"
client_secret = "test-client-secret"